Allow admins to upload images
Kyoso-Team/kyoso-archive pull request #1
Opened 2023-04-04 20:09 UTC by TTTaevas

This introduces "Images" to the database, as well as an `upload` page only accessible to admins, from which you can send images (**although in reality, it's any file, you could use a library to check file type)**
Images get stored and can get accessed at any point by any user through `/images/{id}`, the upload function returns the id (alongside other file-related stuff)

I doubt this is perfect, so please lemme know if there's anything I can do better!

2023-04-04 22:38 UTC, L-Mario564 requested changes
I like the idea for the implementation, aside from the observations there's plans to setup some cloud storage bucket for the files instead of storing them in the DB, not sure if you want to start fiddling with that or leave the implementation as it is and do that later on.

2023-04-04 22:38 UTC, L-Mario564 commented on src/lib/trpc/routes/images.ts
The `obtain` and `upload` procedures should be moved to either:
1. A helper function to be called within the procedure.
```ts
  getSpecificFile: t.procedure.input(z.string()).query(async ({ input, ctx }) => {
    // Do stuff to handle authorization...
    
    // Get the file
    return helperFunctionToGetFile(...);
  })
```
2. A function to be passed as the callback for the query or mutation.
```ts
  getSpecificFile: t.procedure.use(/* Use middleware to handle authorization, if successful, move on to the query */).input(z.string()).query(callbackFunctionToGetFile)
```

This is pointless right now but it will definitely be used later to allow certain users to access/upload only certain files (playtesters for tourney A can't upload to tourney B, a team can only upload and delete their own team banner, etc.)

2023-04-04 22:38 UTC, L-Mario564 commented on src/routes/upload/image/+server.ts
To avoid copy and pasting this code for other file related stuff, an idea could be to upload the file to the file system, in like a `temp` folder or something, and then add a parameter to the post request that can be the procedure I want to call to see I'm allowed to get/delete that file. For example:
`.../upload/image?procedureName=uploadTeamBanner`
```ts
  // In this case it's like calling `caller.images.uploadTeamBanner()`
  let upload = await caller.images[procedureName](img) // tRPC reads the file using `fs` and then handles the rest
```

2023-04-07 00:31 UTC, TTTaevas commented on src/lib/trpc/routes/images.ts
Using middleware to handle authorization, at least on the upload side of things
If accessing the images is also gonna need authorization logic, let me know, I'm guessing most of what would be needed would be like properties on the current `Image` model that indicate what the image is needed for

2023-04-07 00:33 UTC, TTTaevas commented on src/routes/upload/image/+server.ts
Storing the file as a variable while the server checks whether or not the user is allowed to upload it is the solution I'm going for

2023-04-07 02:46 UTC, L-Mario564 approved these changes
Looks good, we can expand upon this later when needed

2023-04-07 02:47 UTC, merged