Improved rules page
Kyoso-Team/kyoso-archive pull request #12
Opened 2023-09-13 03:42 UTC by Entropy-10

This is PR implements improves to the previous rules page markdown editor. The main two issues the PR achieves is added XSS attack prevention and quick formatting tools for less tech savvy users. 

With the XSS implementation, all unwanted scripts or attempts at execution of javascript code are eliminated. Currently it is setup so both before being rendered to preview or being sent to the database, that the raw user's markdown is cleaned of malicious HTML. This does mean the database is now storing HTML and not markdown, so when the user wants to edit their rules it will appear in HTML. This is something that will probably have to change so the clean HTML is converted back into markdown. Finally since the cleaning of the raw user's markdown is done through an api call, I have added proper handling of loading and error states incase of an api error.

For the formatting tools, I have added what I think are the basic and most used markdown formats. They support insert at your cursor or around your selection. For images and links there is a modal that takes the link and then inserts it with the correct formatting.

Finally, I fixed a few small bugs. Mostly notable if you had no rules set in the database, when previewing you could click the undo changes button. This would cause the buttons to disable, preventing you from entering the edit mode which meant you needed to reload the page.

Any feedback on improvements or fix are much appreciated!

https://www.youtube.com/watch?v=ZiE0xtbPpDI

2023-09-14 18:03 UTC, L-Mario564 requested changes
Mostly minor changes requested, except for the link modal prompt, let me know if you think that's a good idea. I know Skeleton allows passing components as modals but not entirely sure how developer friendly that is.

2023-09-14 18:03 UTC, L-Mario564 commented on src/routes/tournament/[tournamentId]/manage/referee-settings/rules/+page.svelte
> +  let delayTimer: NodeJS.Timeout | null = null;
Add `// eslint-disable-next-line no-undef` above this line because my editor complains about `NodeJS` being undefined.

2023-09-14 18:03 UTC, L-Mario564 commented on src/components/general/FormatButtons.svelte
> +        });
Not sure how difficult would be to implement but it would be nice for it to prompt both the label and the link (`[label](link)`).

2023-09-14 18:03 UTC, L-Mario564 commented on src/components/general/FormatButtons.svelte
> +    <button on:mousedown={(e) => e.preventDefault()} on:click={() => handleClick(format)}>
Add a bit of styling to provide user feedback, like changing the background a bit when the button is hovered and also when the button is clicked. Keep the tooltips, those are great.

2023-09-14 18:05 UTC, L-Mario564 commented on src/components/general/FormatButtons.svelte
> +    <button on:mousedown={(e) => e.preventDefault()} on:click={() => handleClick(format)}>
I believe this can be achieved by simply using the `btn` class (assuming you don't want to add your own styles).

2023-09-15 02:47 UTC, Entropy-10 commented on src/components/general/FormatButtons.svelte
> +        });
Yeah that would be nice. I just took a peak at the docs and making a custom component and using it with skeleton doesn't seem too bad. Plus it will set us up in the future if we need custom modals.

2023-09-15 02:48 UTC, Entropy-10 commented on src/components/general/FormatButtons.svelte
> +    <button on:mousedown={(e) => e.preventDefault()} on:click={() => handleClick(format)}>
Sounds good. I'll take a peak at the default behavior or the btn class, but I'll probably end up doing my own thing.

2023-09-15 22:32 UTC, Entropy-10 reviewed
Addressed everything in the mentioned comments. The link modal was a pretty big change, so you might want to take a closer look at that.

2023-09-16 03:04 UTC, L-Mario564 approved these changes
I'll just move the `FormatButtons` import. Other than that, really well done. 👍

2023-09-16 03:05 UTC, merged