Implemented rate limit middleware
Kyoso-Team/kyoso-archive pull request #28
Opened 2024-03-17 23:15 UTC by ArtemOsuskyi

Resolves #24 

This PR introduces tRPC rate limit middleware that can be attached to any procedure via `.use()`

```
const ratelimit = new Ratelimit({
  redis: new Redis({
    url: getEnv().UPSTASH_REDIS_REST_URL,
    token: getEnv().UPSTASH_REDIS_REST_TOKEN
  }),
  limiter: Ratelimit.slidingWindow(1, '10 s')
});
```

Limitations are set in `Ratelimit.slidingWindow` arguments, where (1, '10 s') stands for "1 request per 10 seconds".

Video demonstration:

https://github.com/Kyoso-Team/kyoso/assets/96246908/d1bbf674-dbfa-4e35-9499-369f36a0a0d7

**Note**: Upstash doesn't allow to rate limit any other Redis instances than provided by Upstash themselves, so you'll have to provide your own Upstash Redis credentials. Alternatively we can create a shared development instance and use it instead

2024-03-18 01:08 UTC, L-Mario564 requested changes
Implementation for tRPC procedures looks really good! Just a few minor things that I pointed out in my review.

Will you also address implementing rate limiting in API routes?

2024-03-18 01:08 UTC, L-Mario564 commented on src/lib/server/trpc/middleware.ts
> +import { getEnv } from '../../../../scripts/env';
You can import env like this: `import env from '$lib/server/env';`

2024-03-18 01:08 UTC, L-Mario564 commented on .env.example
> +UPSTASH_REDIS_REST_TOKEN=
Remove line 46 and 49 since there are from the same "group" of variables (all related to Upstash).

2024-03-18 01:08 UTC, L-Mario564 commented on scripts/env.ts
> +  UPSTASH_REDIS_REST_TOKEN: nonEmptyStringSchema
This is the env vars for the scripts, make sure you update the one the app uses in `src/lib/server/env.ts`.

2024-03-18 01:08 UTC, L-Mario564 commented on src/lib/server/procedures/users.ts
> +import { rateLimitMiddleware } from '$trpc/middleware';
Move this line above, type imports must go last.

2024-03-18 01:08 UTC, L-Mario564 commented on src/lib/server/trpc/middleware.ts
> +  limiter: Ratelimit.slidingWindow(1, '10 s')
I know these are likely just test values but pointing it out either way. Maybe we could limit it to 10 requests a second?

2024-03-18 01:21 UTC, ArtemOsuskyi commented
Sure thing! Should API routes be limited to 10 requests/second as well?

2024-03-18 02:12 UTC, L-Mario564 commented
> Sure thing! Should API routes be limited to 10 requests/second as well?

Yep, that should work for those as well.

2024-03-18 02:16 UTC, Entropy-10 commented on src/lib/server/procedures/users.ts
> +import { rateLimitMiddleware } from '$trpc/middleware';
Might want to consider adding a plugin to prettier for sorting imports. Here's one I've personally used and has been great.

https://github.com/IanVS/prettier-plugin-sort-imports

2024-03-18 20:26 UTC, ArtemOsuskyi commented
Done!

2024-03-19 17:20 UTC, L-Mario564 reviewed
Everything looks good, just have the below question.

2024-03-19 17:20 UTC, L-Mario564 commented on src/hooks.server.ts
> +  }
Wouldn't this also affect tRPC procedures? If so, then is there a reason to keep the tRPC middleware instead of just this?

2024-03-19 17:35 UTC, ArtemOsuskyi commented on src/hooks.server.ts
> +  }
I'll do a quick test in the meantime, but I guess it won't do anything to tRPC procedures.

2024-03-19 21:57 UTC, ArtemOsuskyi commented on src/hooks.server.ts
> +  }
Okay so it looks like this if you only have rate limit in hooks.server.ts

![image](https://github.com/Kyoso-Team/kyoso/assets/96246908/13e3512e-d3b7-4a7b-b84b-178e28b0de04)

2024-03-20 16:55 UTC, L-Mario564 approved these changes
All good 👍

2024-03-20 16:55 UTC, L-Mario564 commented on src/lib/server/ratelimit.ts
> +import env from '$lib/server/env';
Move this line to the top.

2024-03-20 16:55 UTC, L-Mario564 commented on src/hooks.server.ts
> +  }
Alright, then we'll keep the tRPC middleware then.

2024-03-20 16:55 UTC, merged