Implemented main user/tournament search procedure
Kyoso-Team/kyoso-archive pull request #39
Opened 2024-03-28 23:23 UTC by ArtemOsuskyi

Resolves #26 

This PR introduces new procedure to search for users/tournaments similarly to how search works on osu website (searching for users/beatmaps from one query input)

2024-04-02 21:35 UTC, L-Mario564 requested changes
Aside form the comments I made, merge master branch into this branch to have it up to date.

2024-04-02 21:35 UTC, L-Mario564 commented on src/lib/server/trpc/router.ts
> +      .with(isBanned)
Don't see where the `isBanned` sub-query is being used in this query.

2024-04-02 21:35 UTC, L-Mario564 commented on src/lib/server/trpc/router.ts
> +          eq(User.osuUserId, +input),
Doing `+input` converts the string into a number, but this might lead to unexpected behavior as a string like `abc` returns `NaN`.

2024-04-02 21:35 UTC, L-Mario564 commented on src/lib/server/trpc/router.ts
> +      .orderBy(({ username }) => asc(username))
Would prefer if it was written as `.orderBy(asc(User.username))`, just a small preference thing.

2024-04-02 21:35 UTC, L-Mario564 commented on src/lib/server/trpc/router.ts
> +    throw trpcUnknownError(err, 'Expiring the session');
This error message should be changed.

2024-04-02 21:35 UTC, L-Mario564 commented on src/lib/server/trpc/router.ts
> +    throw trpcUnknownError(err, 'Expiring the session');
This error message should be changed.

2024-04-02 21:35 UTC, L-Mario564 commented on src/lib/server/trpc/router.ts
> +      .orderBy(({ name }) => asc(name))
Same thing as the other comment about the `orderBy` statement.

2024-04-02 21:35 UTC, L-Mario564 commented on src/lib/server/trpc/router.ts
> +          eq(Tournament.id, +input),
Same thing about the `+input` thing.

2024-04-02 21:35 UTC, L-Mario564 commented on src/lib/server/trpc/router.ts
> +      )
The first 4 conditions should be in the `or` function (which they are right now), and the last one should be an `and`. E.g.:

```ts
and(
  eq(Tournament.deleted, false),
  or(
    // The other conditions...
  )
)
```

2024-04-02 22:17 UTC, ArtemOsuskyi commented
Resolved all comments in latest commit

2024-04-02 23:54 UTC, L-Mario564 requested changes

2024-04-02 23:54 UTC, L-Mario564 commented on src/lib/server/trpc/router.ts
> +import { getSession } from '$lib/server/helpers/api';
Import from `$lib/server/helpers/trpc`.

2024-04-02 23:54 UTC, L-Mario564 commented on src/lib/server/trpc/router.ts
> +      .with(isBanned)
Still don't see where this subquery is used within this main query. I believe there's other parts in the codebase where users are filtered by their ban status, if not, then I can help implementing this bit.

2024-04-03 00:00 UTC, ArtemOsuskyi commented on src/lib/server/trpc/router.ts
> +      .with(isBanned)
God, I did use it when I was resolving comments, but then I came up with `userWhereConditions` and forgot to add it there

2024-04-04 03:15 UTC, L-Mario564 approved these changes

2024-04-04 03:20 UTC, merged