Skip authenticating with Discord if registered
Kyoso-Team/kyoso-archive pull request #4
Opened 2023-04-17 13:30 UTC by TTTaevas

`getDiscordProfile` will likely be reused soon to deal with the process of changing discord accounts
I chose to keep `getProfiles`

okay I won't lie I'm not _super_ satisfied because `ctx.cookies.set('session'...` is used three different times in the file, but I didn't feel the need to rewrite lots of code only for the sake of not repeating, I think it's good enough

2023-04-19 18:11 UTC, L-Mario564 requested changes
Didn't know about getting the osu! user ID from the token, very nice.

2023-04-19 18:11 UTC, L-Mario564 commented on src/lib/trpc/routes/auth.ts
> +      })
I'd like for the Discord data to get updated too.

2023-04-20 12:32 UTC, TTTaevas commented
Using `updateUser` takes care of osu! and discord at the same time, while skipping authenticating with discord (that's the solution you thought about in our discord and it works shockingly well)

But yeah, JWTs, at least for osu!api v2, have the user id in `sub` and the scopes in `scopes`! You can use https://oauth.tools/ or https://jwt.io/ to better understand how that stuff works, if you want

2023-04-21 00:51 UTC, L-Mario564 approved these changes

2023-04-21 00:52 UTC, merged