Implement staff roles tRPC procedures
Kyoso-Team/kyoso-archive pull request #45
Opened 2024-04-24 20:17 UTC by ArtemOsuskyi

Resolves #35 

This PR introduces new staff roles router implementing procedures mentioned in the issue:

- Creating/updating/deleting staff roles
- Swapping order values of staff roles

2024-04-26 02:46 UTC, L-Mario564 requested changes

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/db/schema-utils.ts
> +    uniqueNameTournamentId: 'uni_staff_role_name_tournament_id'
This variable is missing in `db/registrations.ts` line 28 (replacing the string that's already there).

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +}
It seems this function is unnecessary as `getStaffMember` will already check if the tournament exists and if the user is a staff member in that tournament. The only thing to check in the procedures would be the permissions via the `hasPermissions` function, and can be written within the procedure without having to separate it into it's own check function.

Also, in all of these procedures, `tournamentId` should be something the frontend is required to pass as input, so it's not necessary to do a condition for `urlSlug`.

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +      return 'The staff role name must be unique';
"staff role's"

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +        tournamentId: v.number([v.minValue(1), v.integer()])
You can use the `positiveIntSchema` from `lib/schemas.ts` instead for the sake of convenience.

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +    return staffRole;
Returning the created staff role to the client isn't necessary.

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +    return staffRole;
It would be like this:

```ts
try {
      await db
        .with(staffRolesCount)
        .insert(StaffRole)
        .values({
          name,
          tournamentId,
          order: sql<number>`(${
            db.select().from(staffRolesCount)
          })`
        })
    } catch (err) {
      const uqErr = uniqueConstraintsError(err);

      if (uqErr) {
        return uqErr;
      }

      throw trpcUnknownError(err, 'Creating the staff role');
    }
```

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +            name: v.string(),
`name` should have the same schema as the create procedure.

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +    }
This check seems unnecessary.

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +        .then((res) => res);
Add `.limit(2)`.

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +    };
You could also write it as:
```ts
const [sourceStaffRole, targetStaffRole] = staffRoles;
```

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +    const { id } = staffRole;
Seems like an unnecessary check.

2024-04-26 02:46 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +                             AND "order" > ${deletedStaffRole.order}`);
Any reason for not writing this with TS syntax? Also, wouldn't it be better to update orders and then delete the role?

2024-04-26 09:43 UTC, ArtemOsuskyi commented on src/lib/server/procedures/staff-roles.ts
> +                             AND "order" > ${deletedStaffRole.order}`);
No particular reason, just what came to mind first (that and I wasn't sure at first how to do it with TS syntax).

There is really no difference between "update then delete" or vice versa since it's wrapped up in transaction anyway.

2024-04-26 09:56 UTC, ArtemOsuskyi commented on src/lib/server/procedures/staff-roles.ts
> +}
In order to check staff member permissions, I have to get it via `getStaffMember`, but I need to pass tournament ID to do that. According to the issue, not all procedures take tournament ID as an input, hence why I've made this workaround.

Having a separate check function avoids unnecessary code duplication, so I don't see any issue with that

2024-04-27 17:34 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +}
> According to the issue, not all procedures take tournament ID as an input, hence why I've made this workaround.

Ah, that's my bad then, because the tournament ID should be passed to every procedure that needs it.

2024-04-27 17:37 UTC, ArtemOsuskyi commented on src/lib/server/procedures/staff-roles.ts
> +}
Got it, will update accordingly

2024-04-27 17:38 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +                             AND "order" > ${deletedStaffRole.order}`);
> No particular reason, just what came to mind first (that and I wasn't sure at first how to do it with TS syntax).

I see, I definitely suggest to replace the column and table names with TS though, so:
```ts
sql`UPDATE ${StaffRole} SET ${StaffRole.order} = ${StaffRole.order} - 1 WHERE ${StaffRole.tournamentId} = ${deletedStaffRole.tournamentId} AND ${StaffRole.order} > ${deletedStaffRole.order}`
```

2024-04-27 17:41 UTC, ArtemOsuskyi commented on src/lib/server/procedures/staff-roles.ts
> +                             AND "order" > ${deletedStaffRole.order}`);
You might want to take a look at version with Drizzle syntax instead

2024-05-02 04:47 UTC, L-Mario564 requested changes

2024-05-02 04:47 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +      message: 'You do not have the required permissions to create staff roles for this tournament'
Since this function is used in other procedures, I suggest changing the wording from "create staff roles" to "create, modify or delete staff roles".

2024-05-02 04:47 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +        .returning(pick(StaffRole, ['id', 'name', 'tournamentId', 'order']))
Delete this `returning` statement.

2024-05-02 04:47 UTC, L-Mario564 commented on src/lib/server/procedures/staff-roles.ts
> +        .returning(pick(StaffRole, ['tournamentId', 'order']))
You can return only the `order` column since the tournament ID is already passed as an input for the procedure anyways.

2024-05-14 18:09 UTC, L-Mario564 approved these changes
Looks good, I'll just make a few changes, mostly small things. PR should be merged soon. Thanks 👍

2024-05-14 18:52 UTC, merged