Introduce user settings
Kyoso-Team/kyoso-archive pull request #5
Opened 2023-04-21 19:59 UTC by TTTaevas

This PR creates a settings page for users
From this page, users can:
- Switch the public visibility of their Discord tag (on and off)
- Change which Discord account is associated to their Kyoso account
- See the purchases they have made
- View their API key
- Reset their API key **(not implemented)**

(note that `updateUser` is not used for the discord association stuff here, mainly because changing the discord info can't wait (must be instant) for the `updatedAt` to be right, and I couldn't figure out a good way to change such an important function)

2023-04-25 21:43 UTC, L-Mario564 requested changes
A smaller suggestion is to rename the `settings` route to a general `users` one because we might use to update their info and settings and generally manage them. Or you could rename to `userSettings` in case you want to keep user and user settings separate.

2023-04-25 21:43 UTC, L-Mario564 commented on src/lib/trpc/routes/settings.ts
> +    }
You can use the `getStoredUser` middleware instead.

2023-04-25 21:43 UTC, L-Mario564 commented on src/routes/user/settings/+page.svelte
Is there a need to do fetch requests to a regular SvelteKit route instead of using TRPC's browser client? If not then that would save a lot of work and would avoid the need for a `+server.ts` file.

2023-04-26 13:18 UTC, TTTaevas commented on src/routes/user/settings/+page.svelte
There is none
Truth be told, I simply forgot such a thing was possible with TRPC

2023-04-27 23:50 UTC, L-Mario564 approved these changes

2023-04-27 23:51 UTC, merged