Allow admins to manage users from a dedicated page
Kyoso-Team/kyoso-archive pull request #7
Opened 2023-05-11 19:51 UTC by TTTaevas

This PR adds a page where admins can search for users, change their admin status (from admin to non-admin or vice-versa) or completely delete them from the database
Worth noting that most of that stuff is handled through the newly-added `data-display/User.svelte`

PS: ~~Moved `Modal`~~ (edit: cf02da4 was faster lol) and added `Toast` to the root layout, as recommended by Skeleton's documentation
P.P.S: `changeDiscordVisibility` is now actually a mutation, as it should be

2023-05-12 16:00 UTC, L-Mario564 requested changes
The page store being at a component level throws an error and I'm unable to see the entire /admin/users page.

2023-05-12 16:00 UTC, L-Mario564 commented on src/components/data-display/User.svelte
> +  }
These functions should be outside of the component. Should be placed at the page level. This component might be used in other pages and these functions only apply to the /admin/users page. This will also prevent the page store from being accessed at the component level since that breaks Svelte.

2023-05-12 16:00 UTC, L-Mario564 commented on src/components/data-display/User.svelte
> +      managementOptions: Boolean
Use `boolean` instead of `Boolean`.

2023-05-15 14:24 UTC, TTTaevas commented on src/components/data-display/User.svelte
> +      managementOptions: Boolean
oops

2023-05-15 14:34 UTC, TTTaevas commented on src/components/data-display/User.svelte
> +  }
As far as I'm aware, the functions still need to exist where they are actually called

The solution I've found is by passing the functions through the `options` of `<User>` (only when management stuff is needed)
The other solution I've been able to think of is by having the whole management part of users _away_ from the User component, however, that sounds counter-intuitive and probably difficult to design front-end-wise

2023-05-15 14:40 UTC, TTTaevas commented
I have been unable to get any error, so if you still get one, can you record it so I can see what's happening?

By the way, with my latest commit, I've made the search better by triggering the search upon pressing the enter key, and making the search **actually work** as it wasn't working about half the time (as `load` would not always trigger, because the goto `invalidateAll` option was `false`)

2023-05-16 02:09 UTC, L-Mario564 requested changes
Nice catch with the search bar component, didn't realize it was buggy.

I'll leave a suggestion on Discord on how to handle the user actions (and any other actions for any pages with a similar layout).

Also, the error I was getting was cleared up with the latest commit

2023-05-16 02:09 UTC, L-Mario564 commented on src/routes/admin/users/+page.svelte
> +  {#if Boolean($page.url.searchParams.get("search")?.length)}
Didn't catch this the first time but I thought the users wouldn't render because of the error I mentioned but didn't realize I had to input a search term. This is is a bad idea, either add some text saying it's waiting for you to type something or (what we'll usually go for these kind of pages) load the latest 30 (by default) users that have signed up by default and then let the admin user do extra stuff like sorting, filtering and/or searching. Similar to the implementation on the purchases page.

2023-05-17 12:17 UTC, TTTaevas commented on src/components/data-display/User.svelte
> +  }
Ended up going with the other solution, therefore there's no longer any management stuff in the component

2023-05-17 12:22 UTC, TTTaevas commented on src/routes/admin/users/+page.svelte
> +  {#if Boolean($page.url.searchParams.get("search")?.length)}
Now loading users by default (in sign up order)
I have chosen to not create elements that filter or sort as I think that'd be unneeded in this case

2023-05-17 12:29 UTC, TTTaevas commented on src/lib/stores/paginate.ts
> +    goto(url.search || url.href, {keepFocus: true, invalidateAll: true});
`url.search` is a string that includes the sorting and searching options
If it's empty, the `goto` essentially did nothing
There is always sorting in the case of `/admin/purchases` but not in the case of `/admin/users`
So adding `|| url.href` allows you to remove the search filter even if there's no sorting being applied

(tldr, it makes the behaviour consistent regardless of context)

2023-05-20 17:29 UTC, L-Mario564 approved these changes
No issues found, I'll resolve conflicts with master branch.

2023-05-20 17:36 UTC, merged