Implement forms procedures
Kyoso-Team/kyoso-archive pull request #87
Opened 2024-07-23 19:10 UTC by ArtemOsuskyi

Resolves #58 

This PR introduces next procedures:

- Create public/tournament form
- Update form
- Delete form
- Submit form responses

2024-07-26 20:03 UTC, L-Mario564 requested changes
Lots of requested changes, don't worry though, take your time, this is a pretty big feature and PR so that's fine.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/db/forms.ts
> +    uniqueIndexSubmittedByUserId: uniqueIndex('udx_form_response_submitted_by_user_id').on(
This unique index should be both for the form ID and submitted by user ID, since currently the index says that a user can only submit one form response across the entire DB.

2024-07-26 20:03 UTC, L-Mario564 commented on .gitignore
> +.idea
What is this .idea file?

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/helpers.ts
> +}
I think this function should return string or undefined rather than an array of strings. Also, the error messages shouldn't have an exclamation point (nor a period or any other punctuation point at the end).

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/helpers.ts
> +  }
This field can't be changed from true to false nor false to true, and this check only catches the case where it's true and it's being set to false. The check should be: if it's not undefined (a.k.a, true or false) then error.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +        .returning()
Should only return the form ID. Aside from that, `createForm` looks good.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +          message: 'Tournament staff registration has been concluded, form cannot be created'
This could be phrased a bit better: "Tournament staff registrations are closed, form cannot be created"

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +      if (tournament.staffRegsCloseAt || isDatePast(tournament.staffRegsCloseAt)) {
Pretty sure this should be `&&`, since even if it's in the future, the first check will be true and error.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +    const formsCount = await getCount(TournamentForm, eq(TournamentForm.type, type));
There should be two counts, one for general forms and staff regs. forms. If the user is about to create a general tournament form when there's already 5 general tournament forms for that tournament then it should error, and the same goes for staff regs. forms.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +        target: type === 'staff_registration' ? 'public' : target
The following condition seems to be missing:
- If `TournamentForm.type` is `staff_registration`, set `anonymousResponses` to false (do not throw an error).

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +        .returning(pick(Form, ['id']))
Despite the returning statement in the query, nothing is being returned in the transaction. So it should be:

```ts
return await db.transaction(async (tx) => {
  // ...
  return form;
});
```

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +    handleTournamentFormUpdate(ctx, input, tournamentForm);
Since this is an async function, it should be awaited. Also, I don't think it makes sense to update tournament form record before verifying the that the other checks below this comment pass.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +  });
As mentioned in a comment further down, this function shouldn't update the record since other checks are performed that may or may not pass. Also, the following condition is not met:
- If `TournamentForm.type` is `staff_registration`, set `anonymousResponses` to false (do not throw an error).

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +const handleTournamentFormUpdate = async (
This check seems to be missing:
- If the form is for a tournament and `TournamentForm.type` is `staff_registration`, `TournamentDates.staffRegsCloseAt` must be null or in the future.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +      .then((rows) => rows[0]);
You could just select the fields necessary for the checks.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +    });
Don't see why this is here. I don't think this else statement is necessary.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +      });
Don't see why this is here. I don't think this else statement is necessary.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +const deleteForm = t.procedure
A mistake on my part, but `deletedAt` shouldn't be an input, the value for it should be sql`now()` when updating the record.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +      checks.tournamentNotDeleted(tournament).tournamentNotConcluded(tournament);
The following check is not present:
- If the form is for a tournament and `TournamentForm.type` is `staff_registration`, `TournamentDates.staffRegsCloseAt` must be null or in the future.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +        .select()
Only select the necessary fields.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +const updateForm = t.procedure.input(wrap(formUpdateSchema)).mutation(async ({ ctx, input }) => {
Something I forgot to mention in the issue I created was that it should error if the form has been deleted (reminder that forms are soft deleted).

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +const deleteForm = t.procedure
Just like `updateForm` forgot to mention that if the form is already deleted then it should error.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +        .then((rows) => rows[0]);
Only select the necessary fields.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +  const fieldResponsesKeys = fieldResponses.map((response) => Object.keys(response)).flat(99);
Shouldn't the value for the flat function just be `1`?

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +      const fieldResponseIds = fieldsResponses.map((response) => Object.keys(response)).flat(99);
Just like in another comment I made, shouldn't the value for the flat function just be `1`?

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +          fieldsWithResponses: fieldResponseIds
Right here it seems the field with responses are being overwritten. The behavior should be that the responded fields should be added to this array (unless they're already present). Apologies if I didn't explain well in the issue.

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +const submitFormResponse = t.procedure
The following check doesn't seem to be implemented:
- `Form.closeAt` must be null or in the future (to be able to submit).

2024-07-26 20:03 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +        if (tournament.staffRegsCloseAt || isDatePast(tournament.staffRegsCloseAt)) {
Just like in a another comment, pretty sure this should be `&&` instead of `||`.

2024-07-26 21:06 UTC, ArtemOsuskyi commented on src/lib/server/db/forms.ts
> +    uniqueIndexSubmittedByUserId: uniqueIndex('udx_form_response_submitted_by_user_id').on(
Oh yeah true, slipped up my mind

2024-07-26 21:12 UTC, ArtemOsuskyi commented on .gitignore
> +.idea
It's the directory containing project specific settings files. I'll probably just change it as recommended [here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems)

2024-07-26 21:13 UTC, ArtemOsuskyi commented on src/lib/helpers.ts
> +}
:+1:

2024-07-26 21:16 UTC, ArtemOsuskyi commented on .gitignore
> +.idea
You know what, let's keep it ignored. No point in keeping it when I'm the only one who works in WebStorm atm

2024-07-26 21:24 UTC, ArtemOsuskyi commented on src/lib/server/procedures/forms.ts
> +      if (tournament.staffRegsCloseAt || isDatePast(tournament.staffRegsCloseAt)) {
Oh yeah true

2024-07-26 21:28 UTC, ArtemOsuskyi commented on src/lib/server/procedures/forms.ts
> +        target: type === 'staff_registration' ? 'public' : target
I'll add it to insert statement above since TournamentForm don't have anonymousResponses field

2024-07-26 21:32 UTC, ArtemOsuskyi commented on src/lib/server/procedures/forms.ts
> +    handleTournamentFormUpdate(ctx, input, tournamentForm);
While I agree it should be moved down after all the checks, I would argue that it doesn't matter if it'll be awaited or not unless we have to show the form right after the update

2024-07-26 21:37 UTC, ArtemOsuskyi commented on src/lib/server/procedures/forms.ts
> +    });
I tend to avoid unnecessary data in request body if it doesn't do anything, which would be the case if tournamentId is passed but there's no form for this tournament

2024-07-26 21:46 UTC, ArtemOsuskyi commented on src/lib/server/procedures/forms.ts
> +      const fieldResponseIds = fieldsResponses.map((response) => Object.keys(response)).flat(99);
You never know how deep objects can be xd

2024-07-26 21:49 UTC, ArtemOsuskyi commented on src/lib/server/procedures/forms.ts
> +        if (tournament.staffRegsCloseAt || isDatePast(tournament.staffRegsCloseAt)) {
For some reason I've misread the field name as `staffRegsClosedAt` meaning if there's value then staff regs are closed already. My bad on that one

2024-07-28 02:47 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +    handleTournamentFormUpdate(ctx, input, tournamentForm);
The latter is not the case but just thought it'd make sense since the function is async.

2024-07-29 03:34 UTC, L-Mario564 requested changes

2024-07-29 03:34 UTC, L-Mario564 commented on src/lib/helpers.ts
> +  }
The condition should be `data.anonymousResponses !== undefined` and the error should be something like "Form anonymity cannot be changed".

2024-07-29 03:34 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +      message: 'Form is deleted, new responses cannot be submitted'
This is the update form procedure not the response submission one.

2024-07-29 03:34 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +    await db
This should be `tx`.

2024-07-29 03:34 UTC, L-Mario564 commented on src/lib/server/procedures/forms.ts
> +        if (isDatePast(tournament.staffRegsCloseAt)) {
The condition should be `tournament.staffRegsCloseAt && isDatePast(tournament.staffRegsCloseAt`. I know the function accepts undefined but it's not immediately clear what it does in that case (this flaw will be addressed separately by me, right now just make sure undefined is not passed as value).

2024-08-02 04:38 UTC, L-Mario564 approved these changes

2024-09-16 21:19 UTC, merged